### ISSUE TITLE
Add victory sound 

### ISSUE THREAD

**Issue by heyhimansh** [heyhimansh/Guessthenumber#1]
add winning sound through js

**Comment by ramdhanihendrie** [comment]
I am interested in this issue. please assign it to me

**Comment by aniket2003** [comment]
Can you please assign me with this task as i am familiar and efficient with js also i have added sound to website's using js before.

**Comment by aniket2003** [comment]
@heyhimansh  can you please add the hacktoberfest-accepted label to the repositry I just commited.

**Comment by heyhimansh** [comment]
@aniket2003  is this  PR accepted ?

**Comment by aniket2003** [comment]
> @aniket2003  is this  PR accepted ?

I don't know .
 On hactoberfest website it's showing Not Participating can you please help me out ..

**Comment by heyhimansh** [comment]
> > @aniket2003  is this  PR accepted ?
> 
> I don't know . On hactoberfest website it's showing Not Participating can you please help me out ..

I am also facing same problem with my PRs.

**Comment by aniket2003** [comment]
@heyhimansh I think you didn't merged the commit . Can you please look after it .

**Comment by aniket2003** [comment]
Merge my PR.
